### Register a new user without admin
POST http://localhost:8080/register
Content-Type: application/json

{"username": "nipunraj",
 "email": "nipunraj99@gmail.com",
 "password": "123456"
}

### Register a new user with admin
POST http://localhost:8080/register
Content-Type: application/json

{"username": "admin",
 "email": "admin@gmail.com",
 "password": "123456",
 "is_admin": true
}

### LOgin a user
POST http://localhost:8080/login
Content-Type: application/json

{
 "email": "nipunraj99@gmail.com",
 "password": "123456"
}

###get articles which are published
GET http://localhost:8080/articles

### create Articles
POST http://localhost:8080/articles
Content-Type: application/json

{
   "header": "article x",
    "author": "nipunraj",
    "tags": 1,
    "content": "fadfs",
    "status": "published"
} 

### tag creation
POST http://localhost:8080/tags
Content-Type: application/json

{
    "name": "tag2"
}

### tag get request
GET http://localhost:8080/tags

### get articles which are for a particular user.
GET http://localhost:8080/nipun/articles

### get specific article as params 
GET http://localhost:8080/articles/header/admin 3

### get specific article by header or author as query (getByHeaderOrAuthor) 
### here only header (getByHeader) 
### Search functionality.
GET http://localhost:8080/articles/search?header=article 2

### testing (filter)
GET http://localhost:8080/articles/search?tag=1

### edit article of particular user.
### PUT http://localhost:8080/:username/articles/:id
PUT http://localhost:8080/nipunraj/articles/3
Content-Type: application/json

{
   "header": "article y",
    "author": "nipunraj",
    "tags": 2,
    "content": "fadfs",
    "status": "published"
} 